###
//get the subjects
DELETE http://localhost:3131/subjects/22

###
GET http://localhost:3131/runningSubjects
###
GET http://localhost:3131/courses
###
GET http://localhost:3131/topics/1

### 
GET http://localhost:3131/topics

###
GET http://localhost:3131/topicReference/1
### 
# core algorithm
GET http://localhost:3131/getSixDayTopics/1
###

DELETE http://localhost:3131/subjects/35

###
GET http://localhost:3131/topic/1
###
GET http://localhost:3131/runningSubjects